import React, { useState } from "react";
import { useBakery } from "../context/BakeryContext";

export const ReportsView: React.FC<{ onNavigate: (page: string) => void }> = ({ onNavigate }) => {
  const { orders, products, inventory, customers, exportDatabaseJSON, exportOrdersCSV } = useBakery();
  const [activeTab, setActiveTab] = useState<"Overview" | "Customers" | "DataLocker">("Overview");

  const totalSales = orders.filter((o) => o.status === "Paid").reduce((acc, o) => acc + o.total, 0);
  const totalProfit = orders.filter((o) => o.status === "Paid").reduce((acc, o) => acc + o.profit, 0);
  const totalOrdersCount = orders.length;
  const avgOrderValue = totalOrdersCount > 0 ? Math.round(totalSales / totalOrdersCount) : 0;

  const handleSendEmail = () => {
    const subject = encodeURIComponent(`Bakers Brain Daily Summary - ${new Date().toLocaleDateString()}`);
    const body = encodeURIComponent(
      `Here is your latest Bakery Business summary:\n\n` +
      `Total Sales (Realized): ৳${totalSales}\n` +
      `Total Profit (Realized): ৳${totalProfit}\n` +
      `Total Orders Logged: ${totalOrdersCount}\n` +
      `Registered Customers: ${customers.length}\n` +
      `Inventory Items: ${inventory.length}\n\n` +
      `Generated by Baker's Brain Data Locker.`
    );
    window.open(`mailto:?subject=${subject}&body=${body}`, "_blank");
  };

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex justify-between items-center">
        <h2 className="text-lg font-bold text-gray-800">6. Reports & Data Locker</h2>
        <span className="text-[10px] bg-purple-100 text-purple-700 font-bold px-2 py-0.5 rounded-full">
          BI & Storage
        </span>
      </div>

      {/* Tabs */}
      <div className="flex bg-gray-200 p-1 rounded-xl text-xs font-bold text-gray-600">
        {(["Overview", "Customers", "DataLocker"] as const).map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`flex-1 py-1.5 rounded-lg transition ${
              activeTab === tab ? "bg-white text-rose-600 shadow-xs" : "hover:text-gray-900"
            }`}
          >
            {tab === "DataLocker" ? "💾 Data Locker" : tab}
          </button>
        ))}
      </div>

      {/* Tab 1: Overview */}
      {activeTab === "Overview" && (
        <div className="space-y-3">
          <div className="grid grid-cols-2 gap-2.5">
            <div className="bg-white p-3 rounded-xl shadow-xs border border-gray-100">
              <span className="text-[10px] text-gray-400">Total Sales</span>
              <p className="text-base font-black text-gray-900">৳ {totalSales}</p>
            </div>
            <div className="bg-white p-3 rounded-xl shadow-xs border border-gray-100">
              <span className="text-[10px] text-gray-400">Total Profit</span>
              <p className="text-base font-black text-green-600">৳ {totalProfit}</p>
            </div>
            <div className="bg-white p-3 rounded-xl shadow-xs border border-gray-100">
              <span className="text-[10px] text-gray-400">Total Orders</span>
              <p className="text-base font-bold text-gray-900">{totalOrdersCount}</p>
            </div>
            <div className="bg-white p-3 rounded-xl shadow-xs border border-gray-100">
              <span className="text-[10px] text-gray-400">Avg Order Value</span>
              <p className="text-base font-bold text-gray-900">৳ {avgOrderValue}</p>
            </div>
          </div>

          <div className="bg-white p-4 rounded-xl shadow-xs border border-gray-100 space-y-2">
            <h3 className="text-xs font-bold text-gray-800">Top Selling Products</h3>
            {products.length === 0 ? (
              <p className="text-xs text-gray-400">No products registered yet.</p>
            ) : (
              products.map((p) => (
                <div key={p.code} className="flex justify-between items-center text-xs py-1 border-b border-gray-50">
                  <span className="text-gray-700 font-medium">{p.name}</span>
                  <span className="text-gray-900 font-bold">৳ {p.price}</span>
                </div>
              ))
            )}
          </div>
        </div>
      )}

      {/* Tab 2: Customers */}
      {activeTab === "Customers" && (
        <div className="space-y-3">
          {customers.length === 0 ? (
            <p className="text-xs text-gray-400 text-center py-8">No customer history recorded yet.</p>
          ) : (
            customers.map((c) => (
              <div key={c.phone || c.name} className="bg-white p-3.5 rounded-xl shadow-xs border border-gray-100 space-y-2">
                <div className="flex justify-between items-start">
                  <div>
                    <h3 className="font-bold text-sm text-gray-900">{c.name}</h3>
                    <p className="text-xs text-gray-400 font-mono">{c.phone}</p>
                  </div>
                  <span
                    className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                      c.tier === "Best"
                        ? "bg-purple-100 text-purple-700"
                        : c.tier === "Medium"
                        ? "bg-blue-100 text-blue-700"
                        : "bg-gray-100 text-gray-700"
                    }`}
                  >
                    ⭐ {c.tier} Tier
                  </span>
                </div>

                <div className="grid grid-cols-3 gap-1 bg-gray-50 p-2 rounded-lg text-center text-xs">
                  <div>
                    <span className="text-[10px] text-gray-400 block">Orders</span>
                    <span className="font-bold text-gray-800">{c.totalOrders}</span>
                  </div>
                  <div>
                    <span className="text-[10px] text-gray-400 block">Total Spent</span>
                    <span className="font-bold text-gray-800">৳{c.totalSpent}</span>
                  </div>
                  <div>
                    <span className="text-[10px] text-gray-400 block">Profit</span>
                    <span className="font-bold text-green-600">৳{c.totalProfit}</span>
                  </div>
                </div>

                <p className="text-[11px] text-gray-500">📍 {c.address}</p>
              </div>
            ))
          )}
        </div>
      )}

      {/* Tab 3: Data Locker Hub */}
      {activeTab === "DataLocker" && (
        <div className="space-y-3">
          <div className="bg-white p-4 rounded-xl shadow-xs border border-gray-100 space-y-3">
            <h3 className="text-xs font-bold text-gray-800">🗄️ Google Sheets & Backup Center</h3>
            <p className="text-xs text-gray-500">
              Download your database files or forward your structured daily business summary via email.
            </p>

            <div className="space-y-2 pt-2">
              <button
                onClick={handleSendEmail}
                className="w-full bg-purple-600 hover:bg-purple-700 text-white font-bold py-2.5 rounded-lg text-xs shadow transition flex items-center justify-center gap-2"
              >
                ✉️ Send Daily Summary via Email
              </button>

              <button
                onClick={exportOrdersCSV}
                className="w-full bg-teal-600 hover:bg-teal-700 text-white font-bold py-2.5 rounded-lg text-xs shadow transition flex items-center justify-center gap-2"
              >
                📄 Export Orders CSV (Google Sheets Schema)
              </button>

              <button
                onClick={exportDatabaseJSON}
                className="w-full bg-gray-800 hover:bg-black text-white font-bold py-2.5 rounded-lg text-xs shadow transition flex items-center justify-center gap-2"
              >
                💾 Export Full Database JSON
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};